name: ukjobsearch
description: To use reed.co.uk api for job pull
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev



version: 1.0.6+7

environment:
  sdk: '>=2.19.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  

  firebase_auth: ^4.3.0
  email_validator: ^2.1.17

  firebase_core: ^2.13.0
  google_sign_in: ^6.2.1

  image_picker: ^1.0.7
  font_awesome_flutter: ^10.3.0
  intl_phone_field: ^3.1.0

  path_provider: ^2.0.15
  firebase_storage: ^11.2.2
  file_picker: ^8.0.3
  flutter_pdfview: ^1.2.7
  share_plus: ^9.0.0
  http: ^1.1.2
  url_launcher: ^6.1.5
  provider: ^6.1.1

  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.2.2
  tab_container: ^3.5.3
  flutter_spinkit: ^5.2.0

  cloud_firestore: ^4.14.0
  flutter_cached_pdfview: ^0.4.2
  cached_network_image: ^3.3.1
  google_generative_ai: ^0.4.0
  firebase_dynamic_links: ^5.5.5
  syncfusion_flutter_pdfviewer: ^25.2.5
  animated_text_kit: ^4.2.2
  google_fonts: ^6.2.1
  flutter_local_notifications: ^18.0.1
  mailer: ^6.3.0
  functions_framework: ^0.4.3+1
  cloud_functions: ^4.7.6
  permission_handler: ^11.3.1
  firebase_app_check: ^0.2.2+7





 
 

 

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/ca/
    


  fonts:
     - family: Poppins Black
       fonts:
          - asset: fonts/Poppins-Black.ttf
            weight: 600

     - family: Poppins Bold
       fonts:
         - asset: fonts/Poppins-ExtraBold.ttf
           weight: 700
     - family: Kanit Bold
       fonts:
          - asset: fonts/Kanit-Bold.ttf
            weight: 700