// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQNN37TiffhHmEOMn1uVa31l1cy7XLjuA',
    appId: '1:1063846392894:web:efba2a0f0a8fffb587cd6f',
    messagingSenderId: '1063846392894',
    projectId: 'uk-job-search',
    authDomain: 'uk-job-search.firebaseapp.com',
    storageBucket: 'uk-job-search.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrZNuhmtxW6AEEOXpIrHAiRPK9rOvAHMk',
    appId: '1:1063846392894:android:c279345ab8aee9fe87cd6f',
    messagingSenderId: '1063846392894',
    projectId: 'uk-job-search',
    storageBucket: 'uk-job-search.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL5uvwUncNWJNI6AWMblgjJMboyOhDN54',
    appId: '1:1063846392894:ios:69725ed4a74dfffe87cd6f',
    messagingSenderId: '1063846392894',
    projectId: 'uk-job-search',
    storageBucket: 'uk-job-search.appspot.com',
    androidClientId: '1063846392894-6b5jmpla5b025en01cdfcr2vd6rtfei0.apps.googleusercontent.com',
    iosClientId: '1063846392894-ht17n1ngr16277teq253bbhjo2ncj23n.apps.googleusercontent.com',
    iosBundleId: 'com.example.ukjobsearch',
  );
}
